### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [michaelpass/michaelpass.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by michaelpass** [comment]
Will do! Busy day off today. Should have that rollout later this evening w/ screenshot and everything. Thank you for the interest!

**Comment by michaelpass** [comment]
I'll definitely be going GPLV3. Would you recommend against that? I know it's controversial compared to GPLV2, but I want derivative projects to also be Free Software.

**Comment by unixorn** [comment]
Most of my stuff is Apache 2.0, but I have no objections to GPL. The big thing is to have a license at all so that end users can decide if they can use it.

**Comment by michaelpass** [comment]
Got done with my work earlier than expected. Let me know what you think, and I can close this issue. I can flesh out the README.md to cover any dependencies, but for the most part, I just use Oh My ZSH. But, I think I stayed so ZSH-centric that the code should more or less work straight outta the box. I'm testing it on different machines all the time and honing it done to the most universal code I can come up with.

**Comment by unixorn** [comment]
Screenshot looks good. You can use the install instructions from my [tumult](https://github.com/unixorn/tumult.plugin.zsh) plugin as a template if you like - it includes stanzas for antigen, oh-my-zsh and zgenom.

**Comment by michaelpass** [comment]
Okay. Let's close this issue then. And I'll create a new issue for README.md.
✌️

**Comment by michaelpass** [comment]
https://github.com/michaelpass/michaelpass.zsh-theme/issues/2
