### ISSUE TITLE
Update README.md for inclusion in awesome-zsh-plugins

### ISSUE THREAD

**Issue by michaelpass** [michaelpass/michaelpass.zsh-theme#2]
TODO: 
- Installation section on README.md
- Dependencies section on README.md
- Installation section on README.md
- How it Works section on README.md
- Support section on README.md
- Test theme on fresh ZSH install w/ no other dependencies satisfied
- Create separate INSTALL.md

---

From tumult:

Installation:

Oh-My-Zsh
cd ~/.oh-my-zsh/custom/plugins
git clone git@github.com:unixorn/tumult.plugin.zsh.git tumult
Add tumult to your plugin list - edit ~.zshrc and change plugins=(...) to plugins=(... tumult)

**Comment by unixorn** [comment]
When you're done either PR onto https://github.com/unixorn/awesome-zsh-plugins or @ me here and I'll add it, whichever is easier for you.

**Comment by michaelpass** [comment]
@unixorn 
I've got things mostly ready. There might be some funny business in the way I phrased/coded the installation under the Oh My Zsh section of INSTALL.md. 

You'll need to give that a cursory look:
https://github.com/michaelpass/michaelpass.zsh-theme/blob/master/INSTALL.md

I'd prefer to do a PR. Which branch would you like me to initiate the request under?

I'd say the big remaining thing for me to do, would be to clean up the branch name from 'master' to 'main', and get rid of the old code that I have commented out, after I've had the chance to deploy on a fresh Ubuntu 20 (LTS) instance.

Edit:
Would you like me to update the main image to a .gif recording with a flashing cursor? Might be kinda cool, but may put unnecessary strain on older machines. I'm primarily going for portability with this release.

Edit: I'm assuming your https://github.com/unixorn/awesome-zsh-plugins/tree/2021-April-Updates would be the one to go with, no? Lastly, when I get all of my refactoring done, I'll do an official release as version 1.0

**Comment by michaelpass** [comment]
Alrighty then. Code has been refactored. Updating to version 0.2
Let me know what you think of the INSTALL.md. I think the logic is slightly off.

Once I get your suggestions in, I'm ready to release under version 1.0, close this comment and initiate a pull request into your April updates branch.

All The Best,
Michael Pass

**Comment by unixorn** [comment]
I think you don't need the "If you're using bash" section - I don't think the theme will work in bash, though I'd be happy to find out I'm wrong. Other than that, Install.md looks good to me.

You can PR directly against the master branch - the monthly update branches are really for my own use so I don't have to create a ton of branches as I add/update entries to the list.

**Comment by michaelpass** [comment]
I have research obligations at the moment. I should be able to get the code refactored and then reviewed today. 

ETA for V1.0: ~8:00pm, CDT (UTC -05:00)

**Comment by unixorn** [comment]
NP, I didn't mean to rush you, just wanted to give you the feedback on install.md

**Comment by michaelpass** [comment]
No worries my dude, and I didn't feel any rush at all. My research work got out a few hours early. So, I'm back to doing what I love: writing code that helps other people.

**Comment by michaelpass** [comment]
Refactor complete. Releasing as V1.0 release and initiating PR at https://github.com/unixorn/awesome-zsh-plugins
Main change in the refactor is that I moved from deploying as a plugin to deploying as a proper theme.
All The Best,
Michael Pass
